// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
var SUPABASE_URL = "https://ysmzgrtfxbtqkaeltoug.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzbXpncnRmeGJ0cWthZWx0b3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTQzMzcsImV4cCI6MjA2Mjk3MDMzN30.C6WxgdAj3g7fk1IsQRufUhckn-n_eOta_8vR_PVY0d8";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export var supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
